### ISSUE TITLE
Support version 1.21.11 in the near future.

### ISSUE THREAD

**Issue by Laughnt** [oryxel1/GeyserReversion#33]
I am currently running this Geyser extension, and it has been a great project throughout our usage. However, after updating to 1.21.11, it no longer works and throws the error mentioned below.

I truly hope this issue can be addressed in the near future.

Thank you very much.

`[14:18:44 INFO]: [Geyser-Spigot] Started Geyser on UDP port 19133
[14:18:46 ERROR]: [org.geysermc.geyser.event.GeyserEventBus] An exception occurred while executing event GeyserPostInitializeEvent for subscriber org.geysermc.geyser.event.Geys
erEventSubscriber
java.lang.NoSuchMethodError: 'boolean org.geysermc.geyser.network.netty.Bootstraps.setupBootstrap(io.netty.bootstrap.AbstractBootstrap)'
        at oxy.geyser.reversion.GeyserReversion.onGeyserPostInitializeEvent(GeyserReversion.java:118) ~[?:?]
        at Geyser-Spigot.jar//org.lanternpowered.lmbda.Lmbda$1.accept(Unknown Source) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:673) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:281) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:897) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onGeyserEnable(GeyserSpigotPlugin.java:235) ~[?:?]
        at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:219) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[leaf-api-1.21.11-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[leaf-1.21.11.jar:1.21.11-39-d9bdd70]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.11.jar:1.21.11-39-d9bdd70]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[leaf-api-1.21.11-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:698) ~[leaf-1.21.11.jar:1.21.11-39-d9bdd70]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:426) ~[leaf-1.21.11.jar:1.21.11-39-d9bdd70]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[leaf-1.21.11.jar:1.21.11-39-d9bdd70]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:430) ~[leaf-1.21.11.jar:1.21.11-39-d9bdd70]
        at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]
[14:18:46 INFO]: [Geyser-Spigot] Done (6.524s)! Run /geyser help for help!`

<img width="1581" height="545" alt="Image" src="https://github.com/user-attachments/assets/287f388f-6250-44cc-87b0-2b1c73a4085a" />

**Comment by oryxel1** [comment]
should be fixed.
